[MPoW] Onchain crypto stage 3: replace x509 with wasm webpki
crustio/crust pull request #280
Opened 2020-10-27 08:01 UTC by MyronFanQiu

- Fork five libs
    - ring
    - webpki
    - serde_json_no_std
    - serde_no_std
    - serde_derive_no_std
- Remove `verify_identity` from api.rs
- Support `verify_identity` in util.rs
- Test
    - mock test
    - `./target/release/crust --dev --execution Wasm` and use crust-api to register identity
    - build wasm runtime

2020-10-27 09:59 UTC, zikunfan requested changes

2020-10-27 09:59 UTC, zikunfan commented on cstrml/swork/src/utils.rs
> +    let now_func = webpki::Time::from_seconds_since_unix_epoch(1573419050);
Add comments for this number

2020-10-27 09:59 UTC, zikunfan commented on cstrml/swork/src/utils.rs
> +    let chain: Vec<&[u8]> = Vec::new();
More meaningful name?

2020-10-28 02:43 UTC, zikunfan approved these changes
LGTM

2020-10-28 02:48 UTC, LowEntropyBody approved these changes

2020-10-28 02:48 UTC, merged