[GPoS + DSM] New storage staking pot reward mechanism
crustio/crust pull request #393
Opened 2021-01-08 10:07 UTC by MyronFanQiu

Fix #382

2021-01-11 09:08 UTC, zikunfan requested changes

2021-01-11 09:08 UTC, zikunfan commented on cstrml/staking/src/lib.rs
> +                    // DSM staking pot won't be skipped.
`AllowDeath`

2021-01-11 09:08 UTC, zikunfan commented on cstrml/staking/src/lib.rs
> +    fn withdraw_and_arrange_dsm_staking_payout(active_era: EraIndex) {
`distribute_market_staking_payout`?

2021-01-11 09:37 UTC, MyronFanQiu commented on cstrml/market/src/lib.rs
> +        let staking_amount = T::Currency::free_balance(&staking_pot) - T::Currency::minimum_balance();
In order to keep staking pot alive.

2021-01-12 05:33 UTC, zikunfan approved these changes

2021-01-12 05:33 UTC, merged