[Lock] Unlock CRU18, CRU24 or CRU24D6 Module
crustio/crust pull request #561
Opened 2021-04-09 06:18 UTC by MyronFanQiu

2021-04-27 07:33 UTC, zikunfan requested changes

2021-04-27 07:33 UTC, zikunfan commented on cstrml/locks/src/lib.rs
> +            ensure!(Self::start_date().is_some(), Error::<T>::NotStarted);
Add `curr_bn >= start_date`

2021-04-27 07:33 UTC, zikunfan commented on cstrml/locks/src/lib.rs
> +        fn unlock_one_period(origin) -> DispatchResult {
Support unlock multiple periods

2021-04-27 11:02 UTC, zikunfan requested changes

2021-04-27 11:02 UTC, zikunfan commented on cstrml/locks/src/lib.rs
> +        T::Currency::set_lock(
Just set lock without issue CRU?

2021-04-27 11:02 UTC, zikunfan commented on cstrml/locks/src/lib.rs
> +            lock.last_unlock_at = curr_period;
Add comments with steps, and merge 172 and 174 as `Update Locks`

2021-04-27 11:09 UTC, zikunfan requested changes

2021-04-27 11:09 UTC, zikunfan commented on cstrml/locks/src/lib.rs
> +            let free_periods = curr_period.saturating_sub(unlock_date).saturating_sub(lock.lock_type.delay) / T::UnlockPeriod::get();
`unlock_peroids` and `unlock_amount`

2021-04-28 03:53 UTC, MyronFanQiu commented on cstrml/locks/src/lib.rs
> +    fn update_lock(who: &T::AccountId, locked_amount: BalanceOf<T>) {
changed it back

2021-04-28 06:21 UTC, zikunfan approved these changes
lgtm

2021-04-28 07:23 UTC, merged