Support bridge
crustio/crust pull request #732
Opened 2021-08-19 02:18 UTC by MyronFanQiu

2021-08-19 06:32 UTC, zikunfan approved these changes

2021-08-19 06:32 UTC, zikunfan commented on cstrml/bridge/src/mock.rs
> +#![cfg(test)]
Add `ChainSafe` license head?

2021-08-19 06:32 UTC, zikunfan commented on cstrml/bridge_transfer/src/lib.rs
> +// Ensure we're `no_std` when compiling for Wasm.
Change the folder name to `bridge-transfer`

2021-08-20 02:35 UTC, zikunfan commented
Hold on after @BOBOKaa tested

2021-09-09 02:41 UTC, MyronFanQiu commented
use the cherry-pick commit to create a new PR

2021-09-09 02:44 UTC, MyronFanQiu commented on cstrml/bridge/src/mock.rs
> +#![cfg(test)]
done

2021-09-13 05:37 UTC, zikunfan requested changes

2021-09-13 05:37 UTC, zikunfan commented on runtime/src/lib.rs
> +    pub const BridgeTokenId: [u8; 32] = hex_literal::hex!("000000000000000000000000000000608d1bc9a2d146ebc94667c336721b2801");
Will this be changed?

2021-09-13 05:37 UTC, zikunfan commented on runtime/src/lib.rs
> +        ChainBridge: bridge::{Module, Call, Storage, Event<T>} = 100,
Delete this

2021-09-13 05:41 UTC, MyronFanQiu commented on runtime/src/lib.rs
> +    pub const BridgeTokenId: [u8; 32] = hex_literal::hex!("000000000000000000000000000000608d1bc9a2d146ebc94667c336721b2801");
No. It's a format for the word "CRU"

2021-09-15 03:24 UTC, zikunfan approved these changes

2021-09-15 03:26 UTC, merged