[WIP] files v2
crustio/crust pull request #803
Opened 2021-12-23 06:38 UTC by mmyyrroonn

2022-02-07 06:34 UTC, badkk requested changes

2022-02-07 06:34 UTC, badkk commented on cstrml/market/src/lib.rs
> +                            file_info.remaining_paid_count -= 1;
use `saturating_sub`

2022-02-07 06:34 UTC, badkk commented on cstrml/market/src/lib.rs
> +            let maybe_replica = file_info.replicas.remove(&owner);
Didnt need to remove

2022-02-07 06:34 UTC, badkk commented on cstrml/market/src/lib.rs
> +        if Self::filesv2(cid).is_none() { return; }
Change function to `update_replicas`

2022-02-07 06:34 UTC, badkk commented on cstrml/market/src/lib.rs
> +            4u32 => Perbill::from_parts(138888888) * *amount,
Leave some comment

2022-02-07 06:35 UTC, badkk requested changes

2022-02-07 06:35 UTC, badkk commented on cstrml/market/src/lib.rs
> +        if let Some(mut file_info) = Self::filesv2(cid) {
Compatible with old `Files`

2022-03-02 07:26 UTC, mmyyrroonn commented on cstrml/market/src/lib.rs
> +            let maybe_replica = file_info.replicas.remove(&owner);
need to check and then delete

2022-03-23 02:35 UTC, badkk approved these changes

2022-03-23 02:37 UTC, merged